Repository ftn-dnb/isamrs05, pull requests merged in 2019-06, with the labels that each got.

#36 Sediste za brzu rezervaciju
  dnb-travel-frontend/src/components/FlightFastReservationForm.vue
  dnb-travel-frontend/src/components/Navbar.vue
  dnb-travel-frontend/src/router.js
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/FlightController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/FlightReservation.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/FlightService.java
  dnb-travel/src/main/resources/import.sql
Labels: enhancement

#38 Dodata pretraga hotela od strane korisnika. Popravljeni manji bagovi.
  dnb-travel-frontend/src/components/HotelPriceListSettings.vue
  dnb-travel-frontend/src/components/HotelSearch.vue
  dnb-travel-frontend/src/components/Navbar.vue
  dnb-travel-frontend/src/router.js
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/HotelController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/HotelFilterDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/HotelService.java
  dnb-travel/src/main/resources/import.sql
Labels: enhancement

#39 Brza rezervacija karte za let
  dnb-travel-frontend/src/components/AirlineDetailedView.vue
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/AirlineController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/FlightController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/FlightFastReservationDataDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/FlightReservationDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/AirlineService.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/FlightService.java
Labels: enhancement

#40 Dodavanje cene za brzu rezervaciju
  dnb-travel-frontend/src/components/FlightFastReservationForm.vue
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/SeatDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/FlightService.java
Labels: bug, enhancement

#41 Dodata implementacija tekuceg cenovnika. Popravljeni mnogobrojni bago…
  dnb-travel-frontend/src/components/HotelDetailedView.vue
  dnb-travel-frontend/src/components/HotelPriceListSettings.vue
  dnb-travel-frontend/src/components/HotelSearch.vue
  dnb-travel-frontend/src/router.js
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/HotelController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/HotelDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/HotelPriceListDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/HotelPriceListItemDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/UserDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Hotel.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/HotelService.java
  dnb-travel/src/main/resources/import.sql
Labels: bug, enhancement

#42 Hotel rezervacija
  dnb-travel-frontend/src/components/HotelDetailedView.vue
  dnb-travel-frontend/src/components/HotelPriceListSettings.vue
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/DnbTravelApplication.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/config/WebSecurityConfig.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/RoomController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/UserController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/User.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/EmailService.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/RoomService.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/UserService.java
  dnb-travel/src/main/resources/application.properties
  dnb-travel/src/main/resources/import.sql
Labels: bug, enhancement

#43 Opcija za kupovinu karata i logout
  dnb-travel-frontend/src/components/AirlineDetailedView.vue
  dnb-travel-frontend/src/components/Logout.vue
  dnb-travel-frontend/src/components/Navbar.vue
Labels: bug, enhancement

#45 Refaktorisanje code smells-a
  dnb-travel/pom.xml
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/AirlineController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/AuthenticationController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/FlightController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/UserController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/AirlineDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/AirlineStatsDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/FlightDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/FlightFastReservationDataDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Airline.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Flight.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/User.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/AirlineService.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/AirplaneService.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/FlightService.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/UserService.java
Labels: bug, enhancement

#46 Bug airline admin login
  dnb-travel-frontend/src/components/AddCompanyDestination.vue
  dnb-travel-frontend/src/components/AddFlight.vue
  dnb-travel-frontend/src/components/AirlineSettings.vue
  dnb-travel-frontend/src/components/AirlineStats.vue
  dnb-travel-frontend/src/components/FlightFastReservationForm.vue
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/AirlineController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/repository/AirlineRepository.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/AirlineService.java
  dnb-travel/src/main/resources/import.sql
Labels: bug

#47 Airline admin dizajn pocetne stranice
  dnb-travel-frontend/src/components/AdminAirline.vue
Labels: enhancement

#49 Implementirana funkcionalnost rezervacije hotelskih soba. Rezervacija…
  dnb-travel-frontend/src/components/FlightReservation.vue
  dnb-travel-frontend/src/components/HotelDetailedView.vue
  dnb-travel-frontend/src/components/HotelPriceListSettings.vue
  dnb-travel-frontend/src/components/HotelSearch.vue
  dnb-travel-frontend/src/router.js
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/HotelController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/RoomController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/HotelPriceListItemDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/HotelReservationDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/ItemFilterDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Hotel.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/HotelReservation.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/User.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/repository/HotelReservationRepository.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/HotelService.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/RoomService.java
  dnb-travel/src/main/resources/import.sql
Labels: bug, enhancement

#50 Hotel pretraga
  dnb-travel-frontend/src/components/HotelDetailedView.vue
  dnb-travel-frontend/src/components/HotelSearch.vue
Labels: bug, enhancement

#53 Podaci
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Airline.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/AirlinePriceListItem.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Airplane.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Destination.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Flight.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/FlightReservation.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Friendship.java
  dnb-travel/src/main/resources/import.sql
Labels: enhancement

#55 Bug kod prikaza statistike aviokompanije
  dnb-travel-frontend/src/components/AirlineStats.vue
Labels: bug

#59 Transakcije
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/AirlineController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Address.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Airline.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/FlightReservation.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/repository/FlightRepository.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/AirlineService.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/FlightService.java
  dnb-travel/src/main/resources/import.sql
Labels: enhancement

#61 Bug - rezervisanje karte za let koji je prosao
  dnb-travel-frontend/src/components/FlightDetailedView.vue
  dnb-travel-frontend/src/components/FlightList.vue
Labels: bug

#63 Bug duple rezervacije avionskih karata
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/FlightService.java
Labels: bug

#64 Implementacija statistike hotela.
  dnb-travel-frontend/src/components/HotelDetailedView.vue
  dnb-travel-frontend/src/components/HotelStats.vue
  dnb-travel-frontend/src/components/Navbar.vue
  dnb-travel-frontend/src/router.js
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/HotelController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/HotelDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/HotelStatsFilterDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/HotelReservation.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/HotelService.java
Labels: bug, enhancement

#69 Implementacija lokacijskih servisa. Google maps.
  dnb-travel-frontend/package-lock.json
  dnb-travel-frontend/package.json
  dnb-travel-frontend/src/components/AddAirline.vue
  dnb-travel-frontend/src/components/AddHotel.vue
  dnb-travel-frontend/src/components/AdminAirline.vue
  dnb-travel-frontend/src/components/AdminHotel.vue
  dnb-travel-frontend/src/components/AirlineSettings.vue
  dnb-travel-frontend/src/components/HotelDetailedView.vue
  dnb-travel-frontend/src/components/HotelSearch.vue
  dnb-travel-frontend/src/components/HotelSettings.vue
  dnb-travel-frontend/src/components/Navbar.vue
  dnb-travel-frontend/src/main.js
  dnb-travel-frontend/src/plugins/vuetify.js
  dnb-travel-frontend/src/router.js
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/controller/HotelController.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/AddressDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/AirlineDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/dto/HotelDTO.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Address.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Airline.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/model/Hotel.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/repository/AddressRepository.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/AirlineService.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/HotelService.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/UserService.java
  dnb-travel/src/main/resources/import.sql
Labels: bug, enhancement

#74 Manje izmjene.
  dnb-travel-frontend/src/components/HotelDetailedViewFast.vue
  dnb-travel-frontend/src/components/Navbar.vue
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/repository/HotelRepository.java
  dnb-travel/src/main/java/ftn/dnb/dnbtravel/service/HotelService.java
Labels: bug
